// ========================================
// ゲームスタイル定義
// ========================================

const styles = {
  container: {
    minHeight: '100vh',
    background: 'linear-gradient(180deg, #0a0a1a 0%, #1a1a3a 50%, #0a0a1a 100%)',
    fontFamily: '"Noto Sans JP", "Hiragino Sans", sans-serif',
    color: '#e0e0e0',
    overflow: 'hidden',
  },
  header: {
    background: 'linear-gradient(90deg, rgba(20,20,50,0.95) 0%, rgba(40,20,60,0.95) 50%, rgba(20,20,50,0.95) 100%)',
    borderBottom: '2px solid #6b4ce6',
    padding: '12px 24px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    boxShadow: '0 4px 20px rgba(107,76,230,0.3)',
  },
  title: {
    fontSize: '28px',
    fontWeight: 'bold',
    background: 'linear-gradient(90deg, #ff6b9d, #c44dff, #6b9dff)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    textShadow: '0 0 30px rgba(196,77,255,0.5)',
    letterSpacing: '2px',
  },
  gameBoard: {
    display: 'grid',
    gridTemplateRows: '1fr auto 1fr',
    height: 'calc(100vh - 70px)',
    gap: '8px',
    padding: '12px',
  },
  playerArea: {
    display: 'grid',
    gridTemplateColumns: '200px 1fr 280px',
    gap: '12px',
    padding: '8px',
    borderRadius: '12px',
  },
  infoPanel: {
    background: 'rgba(20,20,40,0.8)',
    borderRadius: '12px',
    padding: '12px',
    border: '1px solid rgba(107,76,230,0.3)',
  },
  cardZoneContainer: {
    display: 'flex',
    gap: '12px',
    justifyContent: 'space-between',
  },
  cardZoneItem: {
    flex: '1',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  fieldArea: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  monsterZone: {
    display: 'flex',
    gap: '8px',
    justifyContent: 'center',
    minHeight: '140px',
  },
  cardSlot: {
    width: '100px',
    height: '130px',
    border: '2px dashed rgba(107,76,230,0.4)',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'rgba(20,20,40,0.5)',
    transition: 'all 0.3s ease',
  },
  handArea: {
    display: 'flex',
    gap: '8px',
    justifyContent: 'center',
    padding: '8px',
    minHeight: '150px',
    overflowX: 'auto',
  },
  centerZone: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '40px',
    padding: '12px',
    background: 'linear-gradient(90deg, rgba(20,20,50,0.6) 0%, rgba(40,30,60,0.8) 50%, rgba(20,20,50,0.6) 100%)',
    borderRadius: '12px',
    border: '1px solid rgba(107,76,230,0.3)',
  },
  phaseIndicator: {
    display: 'flex',
    gap: '8px',
  },
  phaseButton: {
    padding: '8px 16px',
    borderRadius: '6px',
    border: 'none',
    cursor: 'pointer',
    fontWeight: 'bold',
    fontSize: '12px',
    transition: 'all 0.3s ease',
  },
  actionButton: {
    padding: '10px 24px',
    borderRadius: '8px',
    border: 'none',
    cursor: 'pointer',
    fontWeight: 'bold',
    fontSize: '14px',
    background: 'linear-gradient(135deg, #6b4ce6 0%, #9d4ce6 100%)',
    color: '#fff',
    boxShadow: '0 4px 15px rgba(107,76,230,0.4)',
    transition: 'all 0.3s ease',
  },
  lifeBar: {
    height: '24px',
    borderRadius: '12px',
    background: 'rgba(0,0,0,0.5)',
    overflow: 'hidden',
    border: '1px solid rgba(255,255,255,0.2)',
  },
  lifeBarFill: {
    height: '100%',
    borderRadius: '12px',
    transition: 'width 0.5s ease',
  },
  spToken: {
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '14px',
    fontWeight: 'bold',
    transition: 'all 0.3s ease',
  },
  modal: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0,0,0,0.85)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modalContent: {
    background: 'linear-gradient(135deg, #1a1a3a 0%, #2a2a4a 100%)',
    borderRadius: '16px',
    padding: '24px',
    maxWidth: '500px',
    width: '90%',
    border: '2px solid #6b4ce6',
    boxShadow: '0 0 50px rgba(107,76,230,0.5)',
  },
  log: {
    background: 'rgba(0,0,0,0.4)',
    borderRadius: '8px',
    padding: '8px',
    maxHeight: '120px',
    overflowY: 'auto',
    fontSize: '11px',
    lineHeight: '1.6',
  },
};

export default styles;
